* Siren RPG

** Premise
   The idea here is to make a system that is
   1. Simple enough to be pick-up and play.
   2. Doesn't require special dice.
   3. Can be learned in an afternoon.
   4. Is general enough to be used in any setting.
   5. Is extensible.

*** Simple Enough to Be Picked up and Played
    It is important that the system is simple. That anyone can sit down, read the book, and get a somewhat intuitive understanding of how the game is to be played.

*** No Special Dice
    For the sake of accessibility, it's important that regular D6 dice are used for the game.
    If everyone is to pick it up and play it, it's also important that everyone has access to the correct dice.
    A set of polyhedral, for example, are easy to come by, but are often much more expensive than a set of D6s, as those are often included with most board games.

*** Can Be Learned in an Afternoon
    It's important that it doesn't take too long to learn the system, particularly not as a GM.
    Spending days trudging through rule-books, only to forget half the rules by the end of it is no way to go.

*** Setting Neutral
    The system should be usable regardless of the setting and genre of the game played.
    It should be dynamic enough to fit Noir, Sci-Fi, Adventure, Fantasy, \&c.

*** Extensible
    Lastly, it should be extensible. 
    Everything in this guide is only meant to be preliminary, if anything needs to be thrown out or replaced, then the player may do so if they wish. 
    Does hacking apply better to the setting than burglary? 
    Then replace one with the other.
